### PR TITLE
Additions and corrections to Diplomacy Deals and URS, fix for World Tracker checkbox bug.

### LINKED ISSUE #340: URS promotion button doesn't work in Australian Summer
[See here](https://github.com/chaorace/cqui/issues/323#issuecomment-282436914) for more info.
I'm waiting to see if URS gets updated soon to fix this minor issue before I try fixing it myself

### PR DESCRIPTION
**Pull request by ricanuck**
Diplo Deal View:
+ Added code from HellBlazer's NQUI mod to display gold per turn available and highlight already possessed resources.

Report Screen (based on JHCD's latest pull request to update URS to 1.7.3, fix #340) :
Corrected some minor bugs:
+ Double (incorrect) Diplomatic deal expenses in Yields tab
+ Fixed diplomatic income/expense yields in Yields tab
+ Row Header labels for Deals tab being repeated in Yields, Resources and Units tabs
+ Minor display bug in turns remaining (added spacing and colon)
+ Report Screen now also remembers last tab opened when re-opening the report.

World Tracker:
+ Fix for the long standing bug that re-enables the World Tracker after change of turn even if player disabled the checkbox the previous turn. Only one line changed (line 247) but we need the entire file for the fix inside the mod.

### CODE REVIEW

**Comment by ricanuck** [comment]
Hey Chao,
I tested all changes in this pull request and they all work fine. You can proceed to commit them.

**Comment by ricanuck** [comment]
Hey Chao,
I also made the report screen remember the last tab opened, so when the report is re-opened, it opens at that last tab. I don't know why Github puts the entire file as added, when I only changed a few lines, but those are all commented. These changes are on top of all the others I previously committed, and those were all based on JHCD's pull request to solve #340 , so you can proceed from there.

**Comment by ricanuck** [comment]
Corrected last problem, uploaded the first time to root instead into the URS directory, you should see the last changes in the file now as expected. Sorry for that.

**Comment by chaorace** [comment]
@ricanuck No worries, hopefully I'll be able to load up the changes and test them out today. My network hardware's been going crazy recently

**Comment by ricanuck** [comment]
@chaorace , if you are short of time, I would suggest you to skip JHCD's remaining pull request, as I based all the changes in mine on that file of his. I checked to make sure of that. Everything seems to be working fine in my custom CQUI build where I do all these changes.

**Comment by chaorace** [comment]
@ricanuck Finally fixed my network hardware last night and the next workshop update is just around the corner, so today's definitely the day I'll be testing this and likely adding it to the main repo. Just reviewing the changes shows a lot of work went into this! :+1:

**Comment by ricanuck** [comment]
Do I get a prize for that? 

I also tested a lot, couldn’t find any issue so far. Some changes are pretty simple, which makes me wonder about the competency of Firaxis’ team... the Worldtracker checkbox issue, in example, was literally ONE word in the entire file to fix it, how can they not fix ONE word in three patches????

Anyways... would love to become your co-owner of the mod and share the weights, if you want to share...

Cheers,

**Comment by chaorace** [comment]
I promise I didn't mean to write a response this long when I started... 😅 

@ricanuck I have similar thoughts concerning the UX when I see some really dumb typo or find myself navigating to the nth menu to get some really basic bit of info, but I think I've come to the realization that the dev team is actually quite competent and concerned with getting things right given the constraints of their work...

It's obvious from looking at some of their code that, at some point, the UX group must have been facing some rather serious time pressure and that they were just doing what they could. I've ended up looking at so much of this group's code over the last 5 months that I can almost tell apart some of the different developers based on just little quirks and code comments. Even reviewing the diffs between patches, you can tell one specific dev seems to be often neurotically making small tweaks to code if he's already in the same file just because it bugs him, while another file has only one big change that's totally isolated, but whose changes always have way more comments. At a point it starts to get weirdly personal! It's just a lot harder to be quite so critical of someone when you start to see yourself and them sitting in the same chair writing the same code (uncomfortable innuendo not intended)

As a time-strapped person myself, I often feel paralyzed by the amount of work there always seems to be left to do and how much time gets sapped by the non-features, like bugfixing and language support. Even with these changes, we've accidentally regressed a feature! (fortunately, that regression is already ready to grab from a PR) I know I'm rambling, but really... the Civ 6 UI is a behemoth and I may have only really touched 10% of it. That's 5 months of often daily work to barely even scratch this thing! I can't not have respect for the UX devs at Firaxis after touching so much of their work and _still_ seeing just how much of it I haven't.

Anyways... I was hoping to rope more people into the "core" group creating the mod and am very open to your proposal. The problem is that it seems to be pretty fatiguing because someone will often pop in, drop 4-5 huge amazing additions, then seemingly cease to exist forever. Ultimately, I'd be happy on-board you as a fully-privileged repository member (that's basically owner status by the way. I don't consider myself the owner of CQUI, but I would still have a couple important permissions like "delete forever" reserved for myself), but I do want to see if you feel the same about the subject in a month or so.

I'm also not comfortable giving someone direct write-access to the repo unless I'm confident in their ability to handle git. Looking at the commit history for this PR shows me that you may still getting your feet wet in terms of wielding git. It [would](https://github.com/chaorace/cqui/commit/33279fb2fe92bfec3a1bebf53f0f405bb44308af) certainly [be hypocritical](https://github.com/chaorace/cqui/commit/66297ff30dc94f8d22b8b1cc3a8ab1bb661c5dc0) to [demand perfection](https://github.com/chaorace/cqui/commit/9aac8bdb446f1f1c4ff532cb7b2ebf71bb5ea634), but I do have a baseline expectation that commits going into the main repos are well formatted. That's not just in terms of the code, but also the commit itself, it needs to be done right on the first try, or else it stays screwed up forever. It's a very dangerous thing to start rewriting history and I need to be able to trust someone to get things right without time travel. This isn't a "you lose I win" clause in the argument for adding you to the project, and it's certainly not a "you need 1000 years more experience to be on my level" thing either. Just, y'know, try taking a step back from the GUIs and try getting your hands dirty with the CLI tool until you grok what's going on under the hood. It's just one of those skills that have a you-know-it-when-you-see-it quality

Anyways, as always, thanks for contributing your time and hard work to CQUI! 👍

**Comment by ricanuck** [comment]
perfectly clear, Chris. You don’t have to explain yourself, even less so at the detail you did, so thanks for taking the time. The little regression in feature (LOCs that the chinese person catched) came from my unquestioned assumption that grabbing JHCD’s PR code was more than enough to ensure continuity given that he has been with you long enough and seems to know what he is doing. Not an excuse, I should have checked, but an explanation.

I will continue to add things here and there the best I can, and when you feel comfortable to share more weight, then let me know. No problem.

This is becoming a little monster, I know and understand... but it is cool when you see it growing, isn’t it?

Anyways, will continue to help the best I can, to make the civ 6 experience better for a lot of people, including ourselves.

Cheers,

**Pull request merged**
