### PR TITLE
create a gitignore and add in intellij project directory

### PR DESCRIPTION
**Pull request by benjaminjackman**
Signed-off-by: Ben Jackman <ben@jackman.biz>

### CODE REVIEW

**Comment by chaorace** [comment]
As much as I like Intellij, it's a bit overkill for the purposes of a lua project that you can't even properly debug outside of the game it's built for. Obviously you're free to use whichever development environment you prefer, but I don't think it's a good idea to be adding specifically IDEA related configuration files at this time. However, I'll accept the gitignore if you create a separate commit for it

**Comment by benjaminjackman** [comment]
:-1:

**Comment by benjaminjackman** [comment]
IDE's serve a lot more purpose than debugging. This is a QOL change for people that use an IDE and a no downside change for everyone else. I don't see the issue.

**Comment by benjaminjackman** [comment]
In any case it's your repo, you've done a great job, I just wanted to express my confusion in the previous comments and not suck up your time in a what goes into the .gitignore discussion so I'll delete the branch, and keep the changes on a locally.

**Comment by chaorace** [comment]
@benjaminjackman I am aware, I just don't see a need to keep a copy of any specific IDE config on the repo. If this were a Java/Scala/Kotlin project I'd feel very differently about the subject, considering Intellij's ubiquity in that space. I apologize if I worded myself harshly in my last comment, I normally like to proofread and edit my responses until they convey exactly what I mean, but I was in a bit of a rush earlier and I guess it shows. Anyways, I hope there's no hard feelings. Your contributions are sincerely appreciated

**Comment by chaorace** [comment]
@benjaminjackman Hmmm, my mistake, you were adding the project files to the .gitignore. That's just a basic failure to comprehend the title on my end. I thought this PR was adding IDEA config files AND a gitignore in the same commit, so I didn't even check the contents of the PR before closing it. That's my fault. Sorry!

**Comment by benjaminjackman** [comment]
ok no worries, that makes a lot more sense, i thought you were asking me to effectively a blank .gitignore so I was pretty confused.

**Comment by benjaminjackman** [comment]
btw if you do have an idea license you might want to give it a shot for lua files, it gets confused for civ6  because they are using a typed lua pre-compiler, but besides for that, being able to ctrl+click to jump around is pretty helpful when exploring 3rd party code. I was using sublime for lua before but ended being pleasantly surprised when i tried intellij on whim for factorio modding and haven't really looked back since.

And given how i wrote the title i can understand the confusion! Feel free to merge the branch or not at your discretion.

**Comment by chaorace** [comment]
I mostly develop away from home on an ultrabook, which renders IntelliJ painfully slow. I'd consider it otherwise, especially since I do have an ultimate license. I'm currently developing using Sublime, which works well enough except in the linting department.

By the way, I'd merge your PR if I could, but you've deleted the branch!

**Comment by benjaminjackman** [comment]
oops ok let me restore

**Pull request merged**
