### PR TITLE
Fixes #152 - Show 2nd highest envoy number in City-states Overview Panel

### LINKED ISSUE #152: Show second-highest envoy number in City-states Overview panel
This is the suggestion mock-up:

289070_20161130104527_1c

_Problem with the Unmodded UI_:

We have to always click into each to check if another civ is closing in on us for city-states for which we are the Suzerain, and we also can't tell if there are others competing for the same city-state.

_Suggestion_:

1. Show the second-highest number of envoys for each city-state on the Overview panel, as shown in the mock-up above.
2. Set the alignment anchor of the second-highest number of envoys to the bottom-right of its label, and position it against the bottom of the space. This is so that when a user uses UI scaling or manually edits font sizes, the two numbers won't overlap and will stay visually appealing.
3. Color in our own number if we are the second-highest number, as shown by the number for Geneva in the mock-up image.

_Aimed Effects of Suggestion_:

1. Tell at a glance whether any of our owned city-state are at risk from competitors.
2. Tell at a glance how fierce the competition is; e.g. Yerevan in the mock-up image is under heavy competition with Japan leading at 9 and another civ right behind Japan. Nobody is even remotely interested in Lisbon. No-one is really competing for Geneva but America has established a strong presence. Nanmadol is under active competition but it's possible to win.
3. Saves lot of clicks when deciding where to send our next Envoy.

### PR DESCRIPTION
**Pull request by Remolten**
I was annoyed by the lack of an easy way to see how many envoys each civilization has, so I decided to add this.

It modifies the UI of the City States Overview Panel, by adding a section at the end of each row that displays which civilization has the second-most envoys, and how many envoys they have.

### CODE REVIEW

**Comment by vttale** [comment]
Screenshot?

**Comment by Remolten** [comment]
Here is a screenshot of this modification in action:

screen shot 2017-01-02 at 3 08 29 pm

**Comment by Remolten** [comment]
The requested changes have been committed. All tab characters were converted into double spaces.

**Comment by chaorace** [comment]
@Remolten Thanks for the quick response! I'm working on setting up a stylebot which automatically checks for this kind of thing so you can get faster feedback in the future. I'm going to do a quick test and merge shortly now

**Comment by chaorace** [comment]
Upon further inspection, I've found that the issue seems to stem from a typo in the modinfo

**Comment by Remolten** [comment]
Apologies for the oversight. I am too used to HTML tags :)

Typos have been fixed and you can now test again to make sure everything is working correctly.

**Comment by chaorace** [comment]
Looking good, merging now!

**Pull request merged**
