### PR TITLE
Russian localization update and fix

### PR DESCRIPTION
**Pull request by e1ectron**

### CODE REVIEW

**Comment by e1ectron** [comment]
@chaorace, One question about this text: "Quarry/Airstrike are moved to alt-key + Q/S"
I suspect translate of "Quarry" may be wrong

**Comment by chaorace** [comment]
Quarry as in a place for mining stone

**Comment by e1ectron** [comment]
translate is right. new locs was added

**Comment by chaorace** [comment]
Thanks! Merging now

**Pull request merged**
