### PR TITLE
Tooltips in loading screen

### PR DESCRIPTION
**Pull request by RatchetJ**
The unique buildings and units now display useful information in the form of tooltips. 

Also in this request is different colors for the civic and tech 50% notifications.

### CODE REVIEW

**Comment by RatchetJ** [comment]
For Issue #18

**Comment by chaorace** [comment]
These changes look great and I'll be testing them shortly. In the future, consider using [pull with rebase](http://gitready.com/advanced/2009/02/11/pull-with-rebase.html) to avoid polluting the commit history when you pull new changes into your branch. As it stands, I'm going to have to squash your changes before merging them to clean this up, which is something I'd prefer not to have to do, considering your PR introduces multiple distinct features. No biggie, just something to consider!

**Comment by chaorace** [comment]
I'm sorry, but some of your changes are going to be unusable for now. I've discovered that FrontEnd modifications do not work until the second loading of a modded save which is strictly Firaxis' fault and something I'd like to wait on before implementing any FrontEnd mods. If anything, so that the rug isn't pulled from under us in some future behavior change to modding these menus. As a result, I'm closing this PR. Please do send another PR my way once Firaxis fixes this issue!

I do like the notification color changes though! I'm gonna git cherry-pick that change directly, so thanks for contributing it!

**Comment by RatchetJ** [comment]
Ok. Thanks for the suggestion. I'm new to git and I guess I'm a little confused on how I should be setting things up. Now, after you've accepted the notification color changes, I should do this rebase thing to make my branch the same as yours?

**Comment by chaorace** [comment]
@RatchetJ

Rebasing is just a way to get the latest changes from my branch without adding a "merge" commit like the two you can see in the history on this PR. A rebase is just overlaying your commits on top of the new base, hence "rebase". [See the top answer here for how to do that](http://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository). If you just want to catch up to the main repo and don't care about preserving your changes, you'll want to "reset" your fork. [See the top answer here for how to do that](http://stackoverflow.com/questions/9646167/clean-up-a-fork-and-restart-it-from-the-upstream).

Generally, you're going to want to reset your branch every time after your changes have been accepted into the main repo so you have a new clean slate to work with and not need to worry about your git history. Just remember that doing this is going to lose any progress that hasn't been accepted into the main branch! If you do have changes that you want to keep after a reset, use "git stash" to stash your changes away for later, doing this saves your changes elsewhere and puts your files back to the clean  state they were in before you started making your stashed changes. To get your stashed changes back, use "git stash pop", this will unstash your changes back to your working directory like they were never gone

**Comment by jacks0nX** [comment]
@RatchetJ I'm in the same boat! ;)

I do the following to keep my local changes, but get everything new from the main one:
- git stash (temporarily stores all local changes)
- git pull --rebase (gets all new changes)
- git stash pop (restores previously stored files)

Works fine for me.

**Comment by benjaminjackman** [comment]
one common practice is to have 2 remote repos as remotes on your local machine.
one is called origin that will point to your fork of this repo in github
the is called upstream that will point at chaorace's repo in github
`git remote add upstream git@github.com:chaorace/cqui.git`

then you can reset your master to chaorace's master both locally and on your github version by doing this
1. `git checkout master` #make sure you are on your master branch
2. `git reset --hard upstream master` #WARNING Will blow away all changes on your local machine! But does not remove any random files that are not trackign by git you will want to use `git clean` to get those ones if necessary
then you can sync your github repo back up with his by force pushing his upstream master to your github repo
3. `git push origin HEAD:master` #WARNING this will overwrite your master branch in your github repo you may need to add a --force to the command but be careful when you do that.

Now that you are back in sync you can make a new branch and check it out for a feature
4. `git checkout -b my-feature`

... make some commits and implement the feature ...

now when you are ready to add your feature in a pull request, presuming you are still on your feature branch i.e. my-feature in this case
5. `git remote update` #this command will tell you local git to update it's view of the outside world
if chaosrace's repo has drifted ahead of yours (which it likely has as he must not sleep and commits stuff constantly)
6. `git rebase upstream/master` #you may have to do some merging here, or not, but if you do do the merges and use `git rebase --continue` to keep rebasing, as rebase rebases one commit at a time from your branch onto chaosraces master or `git rebase --abort` to stop rebasing all together.

now you can push your feature branch back into your github repo which should be called origi
7. `git push origin HEAD` #note you will almost certainly have to use --force if you rebased

at this point you can make a nice clean pull request in the github.com web ui.

8. if there are suggested changes you need to implement for the pull request, check out your feature branch if you need to, commit the changes, and possibly, rebase the feature branch again on to the upstream master, and push your rebased (likely with --force) back up to your origin/master.

if stuff get's messed up from the forcing you may be able to use `git-reflog` to try to recover from it.

(i may have made a couple typos in there as this is a lot of steps)

good luck!

**Comment by jacks0nX** [comment]
Thanks for the detailed explanation. Sounds harder than the programming part itself.. :(
Perhaps I'll just stick to always resetting for now.

**Comment by RatchetJ** [comment]
Yes, thank you guys very much! Much more clear now. I hear you @jacks0nX -- now I can get back to the actual modding.

**Comment by chaorace** [comment]
@jacks0nX Haha, git is a miracle once you learn it. I couldn't live without stash and cherry-pick

**Comment by jacks0nX** [comment]
I guess, but right now it just demotivates me to do anything at all.

**Comment by chaorace** [comment]
@jacks0nX You can always ask me for help on the Gitter IRC. There's a special room for code contributors that is perfect for this kind o& discussion! No need to fumble around, just ask and I'm usually a few minutes away

**Comment by benjaminjackman** [comment]
I am sorry for the somewhat obtuse directions, the last thing I wanted to do was to put you off. it took years to get that workflow down, so don't it expect it to click instantly! It certainly didn't for me. Anyhow it works well for me but it's definitely something you have to grow into. Definitely ask for help on gitter we were all git newbies at one point in time. I am still learning tons of stuff about how to use it. Once you learn it, which can be very frustrating, it's quite powerful. Don't give up :)

**Pull request closed without merging**
