### PR TITLE
French translations

### PR DESCRIPTION
**Pull request by Lctrs**
- [x] cqui.modinfo
- [x] CQUI_Text_General.xml
- [x] BTS_Text.xml
- [x] URS_Text.xml
- [x] MoreLenses_Text.xml
- [x] CQUI_Text_Settings.xml

### CODE REVIEW

**Comment by chaorace** [comment]
Amazing! Sorry for taking so long to get around to reviewing this, I'll be merging this soon assuming no issues

**Comment by Lctrs** [comment]
It's not finished yet. I'll warn you when I finish translating the 2 remaining files.

**Comment by chaorace** [comment]
Ah, alright then

**Comment by chaorace** [comment]
You may also want to consider translating the new lines that will be coming
in with #280

**Comment by Lctrs** [comment]
I'll rebase my changes once it gets merged.

**Comment by Lctrs** [comment]
I'll try to finish the last file this week-end.

**Comment by Lctrs** [comment]
OK. I translated a part of CQUI_Text_Setting.xml. I marked the untranslated lines as TODO for futures translators. I won't do it for now as it's a little too hard for me.

Everything has been rebased against master so you can merge it.

I'll open another PRs if I find improvements for the current translations or finish the translations.

**Pull request merged**
