### PR TITLE
Diplomacy ribbon score

### PR DESCRIPTION
**Pull request by bestekov**
Resolves issue #206 . Moved to put this in the root /UI folder instead of a separate mod folder.

### CODE REVIEW

**Comment by bestekov** [comment]
Fixed the merge conflict. Also here is a screenshot of it in action:

**Comment by chaorace** [comment]
Looking good! Would it be possible to change the military score icon to something round? You can search for icons used in the game with this handy powershell snippet:

`Get-ChildItem -Recurse -Filter "*.xml" | Select-String -Pattern "ICON_"`

**Comment by bestekov** [comment]
So I searched all the icons already (using npp++ find in files for the ICON pattern) but couldn't find any other suitably sized and also round icons. I was hoping to use the red "at war" icon seen in the screenshot on Pericles. But for the life of me I cannot figure out how to reference it. I think it is somehow embedded in a database call or something weird.

I'm open to suggestions on icon, but the only other one that seemed relevant was the red encampment icon.

**Comment by chaorace** [comment]
Hey no worries, most of my issue correspondence is done by phone while I'm at work, since those are the most active hours for the issue tracker. Now that I've had a real chance to sit down and play with the changes, I think there are a few changes that can be made besides the military score icon. For one, I think the vertical spacing is a little squashed and could certainly benefit from some expanding. I think a separator element would do the trick well here. I'd also like to see some kind of backing to the scores like there are for the citizens assigned to districts, maybe set up in such a way that it tucks behind the leader icon without fully encompassing it like [this](http://i.imgur.com/vLNB8pO.png) (excuse the paint mockup)

I think that this may actually be a situation where creating a custom art asset makes sense. Since the Winter Patch it's been possible and I think it'll make for a good test case. I'm gonna take a crack at it and see what I can do. If I come up empty handed I'll still merge your work by the time I go to sleep tonight.

**Comment by chaorace** [comment]
I give up on the custom art for now. I was hoping I could just take the existing square icon and round it out, but it looks like we don't have any way to unpack existing civ 6 icons right now and it's all become one big slog I'd rather not take right now. Will definitely revisit later though

**Pull request merged**
