### PR TITLE
Fixes issue(s) related to Linux & OSX

### PR DESCRIPTION
**Pull request by lettergram**
Tested on Arch Linux (stable build 02/24/2017), works fine and couldn't find any issues.

Fixes issue #333

### CODE REVIEW

**Comment by chaorace** [comment]
Reverting the file to Vanilla Winter Patch is not a good fix. Committing this would break CQUI for everyone on the latest patch, Australian Summer (in other words: Windows users). Feel free to correct me if I've misunderstood what this PR does

If you feel inclined, I would be receptive to creating an OSX/Linux branch if you're willing to create a PR that does that instead

**Comment by lettergram** [comment]
@chaorace I am unable to test this on Windows at the moment, but I believe it should work as well. 

However, a sperate branch would work, as it appears this will happen regularly with FireAxis.

**Comment by chaorace** [comment]
Also, instead of reverting to vanilla files from the Winter Patch, please use the CQUI files prior to the commit that updated them to Australian Summer from this commit: https://github.com/chaorace/cqui/tree/9aac8bdb446f1f1c4ff532cb7b2ebf71bb5ea634

**Comment by lettergram** [comment]
👍 Roger, going to double check that works. Would you be willing to create an OSX-Linux branch?

**Comment by lettergram** [comment]
Alright, so I tested the update(s) and it works fine https://github.com/lettergram/cqui/tree/osx-linux

**Pull request closed without merging**
