### PR TITLE
Added district icons as placable map pins

### PR DESCRIPTION
**Pull request by Rosty**
Additionally changed behavior:
Scrollbar for list of pins
Rightclick on pin in list deletes pin immediately (tooltip added)
Return key immediately creates pin from popup

Adjusted modinfo with new files and reordered lines alphabetically.

### CODE REVIEW

**Comment by chaorace** [comment]
Just finished testing and it works splendidly. Merging now

**Comment by dubert** [comment]
@chaorace for me, after I place them, they show up on the map as black hexagons. Do you see this behavior? Do you think it's because it's using the image as a mask? I could provide the district icons as masks if they don't exist

**Comment by jacks0nX** [comment]
Happened to me from time to time too, but couldn't reliably reproduce it. Might depend on the civ you're playing, since they're all given unique colors which have influence on the pin.

Are they always black? Also in a different game?

**Comment by dubert** [comment]
Let me do some more testing this evening and get back to you. I only tried it in one game as the Germans.

**Comment by chaorace** [comment]
There's also a dimming option built into flags. Try getting the bugged pin from the MapPinManager and playing with SetDim

**Comment by jacks0nX** [comment]
Yep, definitely depends on the civ. I'm in a germany game atm, same happens to my pins.

**Comment by jacks0nX** [comment]
The dim doesn't seem to be the problem. I suspect that the check whether it's a default map pin icon doesn't work correctly, since remove that line makes the default ones look wrong and the district ones correct.

**Pull request merged**
