### PR TITLE
fix recommendation icons in tech and civic tree

### PR DESCRIPTION
**Pull request by ProustIdee**

### CODE REVIEW

**Comment by ProustIdee** [comment]
Do you know why it's showing so many changes involving whitespace? There's only a few lines of actual changes. I'm using Atom to make my edits.

**Comment by chaorace** [comment]
Using the Compare plugin in Notepad++ there's an option to ignore whitespace changes. You can also just directly compare the old game files to the new ones instead of comparing the mod files to the new base files. Obviously you can't get them anymore if you didn't back them up, so I'll just email you a copy of my backup instead

**Comment by chaorace** [comment]
Oh I see, you mean in the git changes!  Yeah that's probably due to copy-pasting lines or something. You can use a tool like sourcetree to discard changes to a file piecemeal so you can clean those up before committing. It's not a big deal either way, but in the future it may be a good idea to give the diff a onceover before pushing it

**Comment by chaorace** [comment]
Anyways, would it be possible if you could resubmit this PR with a cleaner changelog?

**Comment by chaorace** [comment]
No worries, fixed it myself 👍

**Pull request merged**
