### PR TITLE
Icon Based Housing on City Panel Overview

### PR DESCRIPTION
**Pull request by Frozen-In-Ice**
Icon Based Housing on City Panel Overview

### CODE REVIEW

**Comment by Frozen-In-Ice** [comment]
Apparently this also includes the changes I made to Great People Popups now because I have no idea how Github works.

**Comment by vttale** [comment]
Can you share a screenshot, please?

**Comment by Frozen-In-Ice** [comment]
Sure:
Housing Changes
screenshot 2017-01-02 15 32 15

Great Person Popup Changes
screenshot 2017-01-02 15 32 35
screenshot 2017-01-01 22 43 19

**Comment by NoShotz** [comment]
This looks awesome, and thanks for fixing the GP panel scroll bars being out of their tracks, it was really annoying. Hope this gets merged soon.

**Comment by Frozen-In-Ice** [comment]
Made it so that turns left indicator always rounds up (was previously rounding to nearest whole number, but in game terms .3 turns is really 1 more turn), and fixed scroll bar to be better placed. Replaced tabs with spaces to better match style guide in code.

Screenshots:
Windowed mode better scroll bar placement
screenshot 2017-01-02 20 45 19

Slightly changed recruit button placement so that it fit better with my other changes. I had forgotten to test for this previously, but it should be good now!
screenshot 2017-01-02 21 02 31

**Comment by chaorace** [comment]
Looks good, merging now!

**Pull request merged**
