### PR TITLE
Score display

### PR DESCRIPTION
**Pull request by bestekov**
#206 - Implemented this feature. There could be future enhancements added for toggling this on/off in CQUI menu or for sorting player icons by score.

### CODE REVIEW

**Comment by chaorace** [comment]
New folders at the root of the mod are reserved for integrated mods that live independently of cqui as a rough compromise which makes them easier to update when the mod author releases a new version. Seeing as this PR is direct-to-cqui feature, it doesn't make sense to make this kind of compromise

**Comment by bestekov** [comment]
Oh okay that's my misunderstanding then. Okay here's what I'm going to do. I'm going to discard all this. Add the base unedited file to the \UI folder then make a new commit that combines all my changes into one commit. Sound good?

**Comment by chaorace** [comment]
This is the kind of PR that I can just squash at the end anyways, so feel
free to treat your commit history however you prefer. Despite any perceived
ire, I really do appreciate your contribution, so thanks!

**Comment by bestekov** [comment]
No ire detected! Just misunderstood the folder structure. I submitted a new PR.

**Pull request closed without merging**
