### PR TITLE
Diploview extended tooltips

### PR DESCRIPTION
**Pull request by ricanuck**
Extends relationship tooltips for the vertical diplo ribbon inside diplo view.

### CODE REVIEW

**Comment by chaorace** [comment]
The commit history is incorrect for this PR, still containing the history from your last PR. Please base all future PRs on fresh branches instead, you can read more about why/how [here](https://github.com/chaorace/cqui/pull/344#issuecomment-282526276). From the looks of it, you did try using a separate branch for this PR, so that indicates to me that the branch you based this new one on (master, perhaps?) doesn't have a correct history. To fix this, use `git reset --hard upstream/master` while you've checked out your master branch (be cautious, however, doing this will lose any unique changes you've made to the master branch that cause it to diverge from the main repo). If you haven't already, you'll need to first add the main repo as a remote using 
`git remote add upstream https://github.com/chaorace/cqui.git`

Since this is a relatively minor history issue, I'll just correct it myself using my temporary PR access rights, but please use `git log` in the future to check your commit history before pushing to ensure that it's correct

**Comment by ricanuck** [comment]
Impossible, this was made in a completely fresh branch from a completely new repository fork. How would what you say be possible????

**Comment by chaorace** [comment]
Here's [a screengrab](http://i.imgur.com/cNDyESU.png) of the history from the commits tab if you don't believe me. It's entirely possible that something was overlooked and the history issue slipped through the cracks. Like I said, in the future just double-check with git log before pushing, this kind of thing happens to the best of us

**Comment by chaorace** [comment]
Anyways, I've rewritten the branch history to be correct. I'll test the change now and merge in just a minute

**Comment by ricanuck** [comment]
Oh nonono, that is not an OLD commit history, I changed the modinfo file again to include the new file, and then again to correct the issue with the tab/spacing... that is not OLD, is part of this commit/branch.

**Comment by chaorace** [comment]
*facepalm* woops, let me restore that then

**Comment by ricanuck** [comment]
"happens to the best of us"
hehe

**Comment by ricanuck** [comment]
I am creating new repos every time I want to contribute, to avoid any type of issues...

**Comment by chaorace** [comment]
Hey it looked identical to the last PR commit history almost word-for-word, thanks for bearing with my temporary bout of incompetence

**Comment by ricanuck** [comment]
still good for a late night laugh, isn't it? No worries, I am no master of the hub at all, not yet anyways...

**Comment by chaorace** [comment]
Late night laugh indeed! Anyways, I've fixed the commit to actually include the committed changes. Apologies about the unnecessary mutation in history, the PR credit should still go solely to you on merging

**Comment by ricanuck** [comment]
Where are you btw? East coast?

**Comment by chaorace** [comment]
Yes, though this isn't a natural time for me to be awake. I just finished a project rollout at work yesterday and passed out as soon as I got home. I figured I would take advantage of the unusual opening in my time now that I've woken up.  Apologies if I've woken you!

**Comment by ricanuck** [comment]
nah, PNW here, 2300 hours

**Pull request merged**
