### PR TITLE
Extended tooltips for relationship icon

### PR DESCRIPTION
**Pull request by ricanuck**
Extends the relationship icon tooltip to show diplo modifiers. Solves #356 .

### CODE REVIEW

**Comment by ricanuck** [comment]
Better?

**Comment by andydtoma** [comment]
Very good tooltip.
It would be nice to attach it to the relationship icons on the left navigation bar when discussing with an AI leader.

**Comment by ricanuck** [comment]
That’s a good idea. Shouldn’t be hard to do. Will go into that in the next few days.

Just to be clear, you mean the vertical diplo ribbon, correct?

**Comment by ricanuck** [comment]
@andydtoma : added in #393 .

**Pull request merged**
