### PR TITLE
GP dialog, mappin enhancements

### PR DESCRIPTION
**Pull request by jacks0nX**
See issues #40  and #42. Hope I committed correctly now. :o

### CODE REVIEW

**Comment by chaorace** [comment]
Absolutely fantastic, I'm testing the changes now

**Comment by chaorace** [comment]
Some outstanding issues with the current changes:

Wonder district icon is missing some string data, which makes the tooltip a bit ugly


The great prophet panel is stashed to the right when prophets are still available, but once they're all claimed it moves back to the center and doesn't hide

**Comment by jacks0nX** [comment]
Huh, I don't even know what kind of district that is, probably wrong data. Filtered out now.
Can you give me a save file for the GP one? Worked fine on my side.

**Comment by chaorace** [comment]
Here's the save: https://docs.google.com/uc?id=0BzRHuYM0ypGoeXRRYWV6Mm1HNEU

If you'd like to be sure you're on exactly the same version I am, [follow these instructions](https://help.github.com/articles/checking-out-pull-requests-locally/)

**Comment by jacks0nX** [comment]
Hm, you started a new game for this, right? Weird, values that are set for every other item in your save, and every item in my save, is completely missing for the great prophet in your save. DOn't know why yet.

**Comment by chaorace** [comment]
This is a save I test lots of things on, but I I never save the progress after finishing my tests, so it's effectively a clean slate

**Comment by chaorace** [comment]
Any progress?

**Comment by jacks0nX** [comment]
Pins are fixed, didn't find a solution to the GP problem yet. Can't explain why your data is null.

**Comment by jacks0nX** [comment]
Is there a way to remove files from a pull request? Otherwise I'd close this one and just create a new one with the fixed pins.

**Comment by chaorace** [comment]
@jacks0nX You should just be able to add the new changes to your existing fork and they'll be part of the PR too. For the GP problem, I think it'll just be best if we nixx hiding the panel for now if we can't iron out this behavior.

**Comment by zyxpsilon** [comment]
I feel the **GreatProphet** should *NOT* get hidden by any means.. only pushed to the far right is enough.
BUT -- i do have a recommendation for that panel. Haven't yet done the necessary MockUP to visualize what i mean, yet i can explain what should solve most issues -- verbally here...

1) Discard all instances of "RECRUIT PROGRESS" & "or Recruit with Patronage" except for the GreatProphet slot as a unique indirect reference to context. To make room for...

2) A re-calibrated panel that prevents the Progress blocks from sharing their side bars. It's quite simple.. you'd gain at least 16 pixels by compressing the two Patronage cost boxes together while leaving only 4 pixels between them. Then, you also reduce all the growth meterbars & the Biography button by the same amount (16).
Secondly, i we get to keep (as much as i am still hoping for & demonstrated with an image in a post on CivFanatics) the Vanilla Framework panels (Modal Backgrounds).. it also can crop its own 16 pixels off the middle part to match any total width(s).

3) Long names like _"Ludwig von Beethoven"_ might overlap the Panel side lines a little.. unless we keep (again) the Vanilla structure that puts a dividing line for the ERA reference.

I'll return with direct visual hints later.

**Comment by jacks0nX** [comment]
I'm not quite sure what you mean, but I'll gladly wait for a mockup! :p

**Comment by jacks0nX** [comment]
Jesus, I messed up that whole commit/push/ stuff again.. I'll just close this and create a new one.

**Comment by zyxpsilon** [comment]
Copy/Paste from #40 for your convenience!
panel_before-after

**Pull request closed without merging**
